/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema;
import Clases.Carrito1;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import movimiento.MoverComp;

/**
 *
 * @author CRISTHIAN
 */
public class Productos extends javax.swing.JFrame {
    
    //carrito1 ca=new carrito1();
    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Productos");

    }
 
   public void tipoP(int orden1){
        orden=orden1;
    }

   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        opciones = new Sistema.PanelRound();
        btnsm = new Sistema.PanelRound();
        lblm = new javax.swing.JLabel();
        inicio = new javax.swing.JPanel();
        lblinicio = new javax.swing.JLabel();
        lbli = new javax.swing.JLabel();
        favorito = new javax.swing.JPanel();
        lblfavorito = new javax.swing.JLabel();
        lblf = new javax.swing.JLabel();
        carrito = new javax.swing.JPanel();
        lblcarrito = new javax.swing.JLabel();
        lblc = new javax.swing.JLabel();
        configuracion = new javax.swing.JPanel();
        lblMood = new javax.swing.JLabel();
        lblconfiguracion = new javax.swing.JLabel();
        salir = new javax.swing.JPanel();
        lblsalir = new javax.swing.JLabel();
        lbls = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        salir1 = new Sistema.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        product1 = new javax.swing.JPanel();
        lblp1 = new javax.swing.JLabel();
        lblimg1 = new javax.swing.JLabel();
        product2 = new javax.swing.JPanel();
        lblp2 = new javax.swing.JLabel();
        lblimg2 = new javax.swing.JLabel();
        product3 = new javax.swing.JPanel();
        lblp3 = new javax.swing.JLabel();
        lblimg3 = new javax.swing.JLabel();
        chk1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        panelP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblpago = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opciones.setBackground(new java.awt.Color(70, 143, 175));
        opciones.setRoundBottomRight(30);
        opciones.setRoundTopRight(30);
        opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsm.setBackground(new java.awt.Color(64, 128, 156));
        btnsm.setRoundBottomLeft(45);
        btnsm.setRoundBottomRight(45);
        btnsm.setRoundTopLeft(45);
        btnsm.setRoundTopRight(45);
        btnsm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblm.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblm.setForeground(new java.awt.Color(255, 255, 255));
        lblm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblm.setText("≡");
        lblm.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblm.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        lblm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblmMouseReleased(evt);
            }
        });
        btnsm.add(lblm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 45, 45));

        opciones.add(btnsm, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 25, -1, -1));

        inicio.setBackground(new java.awt.Color(70, 143, 175));
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioMouseExited(evt);
            }
        });
        inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.png"))); // NOI18N
        inicio.add(lblinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, 37, 35));

        lbli.setBackground(new java.awt.Color(255, 255, 255));
        lbli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbli.setForeground(new java.awt.Color(255, 255, 255));
        lbli.setText("Inicio");
        inicio.add(lbli, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 18, -1, -1));

        opciones.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 60));

        favorito.setBackground(new java.awt.Color(70, 143, 175));
        favorito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favoritoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favoritoMouseExited(evt);
            }
        });
        favorito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblfavorito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/favoritos.png"))); // NOI18N
        favorito.add(lblfavorito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, 37, 35));

        lblf.setBackground(new java.awt.Color(255, 255, 255));
        lblf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblf.setForeground(new java.awt.Color(255, 255, 255));
        lblf.setText("Favoritos");
        favorito.add(lblf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 18, -1, -1));

        opciones.add(favorito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 60));

        carrito.setBackground(new java.awt.Color(70, 143, 175));
        carrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carritoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carritoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carritoMouseExited(evt);
            }
        });
        carrito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        carrito.add(lblcarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, 37, 35));

        lblc.setBackground(new java.awt.Color(255, 255, 255));
        lblc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblc.setForeground(new java.awt.Color(255, 255, 255));
        lblc.setText("Carrito");
        carrito.add(lblc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 18, -1, -1));

        opciones.add(carrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 60));

        configuracion.setBackground(new java.awt.Color(70, 143, 175));
        configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configuracionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configuracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configuracionMouseExited(evt);
            }
        });
        configuracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMood.setBackground(new java.awt.Color(255, 255, 255));
        lblMood.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMood.setForeground(new java.awt.Color(255, 255, 255));
        lblMood.setText("Modo Oscuro");
        configuracion.add(lblMood, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, -1));

        lblconfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mood.png"))); // NOI18N
        configuracion.add(lblconfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 15, 37, 35));

        opciones.add(configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 60));

        salir.setBackground(new java.awt.Color(70, 143, 175));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/csesion.png"))); // NOI18N
        salir.add(lblsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, 37, 35));

        lbls.setBackground(new java.awt.Color(255, 255, 255));
        lbls.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbls.setForeground(new java.awt.Color(255, 255, 255));
        lbls.setText("Cerrar sesión");
        salir.add(lbls, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 18, -1, -1));

        opciones.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 210, 60));

        main.add(opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(-125, 0, 210, 533));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir1.setBackground(new java.awt.Color(247, 247, 247));
        salir1.setForeground(new java.awt.Color(204, 204, 204));
        salir1.setRoundBottomLeft(30);
        salir1.setRoundBottomRight(30);
        salir1.setRoundTopLeft(30);
        salir1.setRoundTopRight(30);
        salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salir1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salir1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                salir1MouseReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("←");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout salir1Layout = new javax.swing.GroupLayout(salir1);
        salir1.setLayout(salir1Layout);
        salir1Layout.setHorizontalGroup(
            salir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salir1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        salir1Layout.setVerticalGroup(
            salir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salir1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 32));

        product1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product1MouseClicked(evt);
            }
        });
        product1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblp1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        product1.add(lblp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 60, 21));
        product1.add(lblimg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 19, 140, 140));

        jPanel7.add(product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 180, 200));

        product2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblp2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        product2.add(lblp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 21));
        product2.add(lblimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 140));

        jPanel7.add(product2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 180, 200));

        product3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblp3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        product3.add(lblp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 21));
        product3.add(lblimg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 140));

        jPanel7.add(product3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 180, 200));

        chk1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chk1.setText("Agregar");
        jPanel7.add(chk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Agregar al carrito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 150, 40));

        chk2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chk2.setText("Agregar");
        jPanel7.add(chk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        chk3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chk3.setText("Agregar");
        jPanel7.add(chk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        main.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 730, 430));

        panelP.setBackground(new java.awt.Color(144, 224, 239));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Total a pagar:");

        lblpago.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblpago.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("S/.");

        javax.swing.GroupLayout panelPLayout = new javax.swing.GroupLayout(panelP);
        panelP.setLayout(panelPLayout);
        panelPLayout.setHorizontalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2))
                    .addGroup(panelPLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblpago, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelPLayout.setVerticalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblpago, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        main.add(panelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, -1, 130));

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 949, 533));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmMouseClicked
        if (opciones.getX()==-125)
        MoverComp.Derecha(opciones, 2, 1, 0);
        else
        MoverComp.Izquierda(opciones, 2, 1, -125);
    }//GEN-LAST:event_lblmMouseClicked

    private void lblmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmMousePressed
        if (lblMood.getText().equals("Modo Oscuro"))
        btnsm.setBackground(new Color(44,107,135));
        else
        btnsm.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_lblmMousePressed

    private void lblmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmMouseReleased
        if (lblMood.getText().equals("Modo Oscuro"))
        btnsm.setBackground(new Color(64,128,156));
        else
        btnsm.setBackground(new Color(40,40,40));
    }//GEN-LAST:event_lblmMouseReleased

    private void inicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseEntered
        if (lblMood.getText().equals("Modo Oscuro"))
        inicio.setBackground(new Color(44,107,135));
        else
        inicio.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_inicioMouseEntered

    private void inicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseExited
        if (lblMood.getText().equals("Modo Oscuro"))
        inicio.setBackground(new Color(70,143,175));
        else
        inicio.setBackground(new Color(27,27,27));
    }//GEN-LAST:event_inicioMouseExited

    private void favoritoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoritoMouseEntered
        if (lblMood.getText().equals("Modo Oscuro"))
        favorito.setBackground(new Color(44,107,135));
        else
        favorito.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_favoritoMouseEntered

    private void favoritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoritoMouseExited
        if (lblMood.getText().equals("Modo Oscuro"))
        favorito.setBackground(new Color(70,143,175));
        else
        favorito.setBackground(new Color(27,27,27));
    }//GEN-LAST:event_favoritoMouseExited

    private void carritoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carritoMouseEntered
        if (lblMood.getText().equals("Modo Oscuro"))
        carrito.setBackground(new Color(44,107,135));
        else
        carrito.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_carritoMouseEntered

    private void carritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carritoMouseExited
        if (lblMood.getText().equals("Modo Oscuro"))
        carrito.setBackground(new Color(70,143,175));
        else
        carrito.setBackground(new Color(27,27,27));
    }//GEN-LAST:event_carritoMouseExited

    private void configuracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configuracionMouseEntered
        if (lblMood.getText().equals("Modo Oscuro"))
        configuracion.setBackground(new Color(44,107,135));
        else
        configuracion.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_configuracionMouseEntered

    private void configuracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configuracionMouseExited
        if (lblMood.getText().equals("Modo Oscuro"))
        configuracion.setBackground(new Color(70,143,175));
        else
        configuracion.setBackground(new Color(27,27,27));
    }//GEN-LAST:event_configuracionMouseExited

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        if (lblMood.getText().equals("Modo Oscuro"))
        salir.setBackground(new Color(44,107,135));
        else
        salir.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        if (lblMood.getText().equals("Modo Oscuro"))
        salir.setBackground(new Color(70,143,175));
        else
        salir.setBackground(new Color(27,27,27));
    }//GEN-LAST:event_salirMouseExited

    private void product1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_product1MouseClicked
    double total=0;
    int orden;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Carrito1 obj=new Carrito1();
        Principal p=new Principal();
        boolean p1=chk1.isSelected();
        boolean p2=chk2.isSelected();
        boolean p3=chk3.isSelected();
        double subt=0;
        double totalc=0, totalz=0,totala=0, totalp=0;
        if(p1){
            subt+=precio1;
        }
        if(p2){
            subt+=precio2;
        }
        if(p3){
            subt+=precio3;
        }
        
        switch(orden){
            case 0:
                totalz+=subt;
                obj.setSubTotal(totalz, orden);break;
            case 1:
                totalp+=subt;
                obj.setSubTotal(totalp, orden);break;
            case 2:
                totalc+=subt;
                obj.setSubTotal(totalc, orden);break;
            case 3:
                totala+=subt;
                obj.setSubTotal(totala, orden);break;
        }
        total = obj.totalPago();
        
        lblpago.setText(""+total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir1MouseClicked
        Principal obj=new Principal();
        obj.setVisible(true);
        Principal.lblpago2.setText(lblpago.getText());
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_salir1MouseClicked

    private void salir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir1MouseEntered
        salir1.setBackground(new Color(231,231,231));
    }//GEN-LAST:event_salir1MouseEntered

    private void salir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir1MouseExited
        salir1.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_salir1MouseExited

    private void salir1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir1MousePressed
        salir1.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_salir1MousePressed

    private void salir1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir1MouseReleased
        salir1.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_salir1MouseReleased

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        if(JOptionPane.showConfirmDialog(null, "¿Esta seguro de salir?", "Alerta!", JOptionPane.YES_NO_OPTION)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_salirMouseClicked

    private void carritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carritoMouseClicked
        Carrito car=new Carrito();
        if (lblpago.getText().equals("")||lblpago.getText().equals("0.0")){
        JOptionPane.showMessageDialog(null, "No ha seleccionado ningún producto.", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
        car.setVisible(true);
        Carrito.jLabel5.setText(lblpago.getText());
        this.setVisible(false);
        }
    }//GEN-LAST:event_carritoMouseClicked

    private void configuracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configuracionMouseClicked
        if (lblMood.getText().equals("Modo Claro")){
            main.setBackground(Color.WHITE);
            opciones.setBackground(new Color(70,143,175));
            lblMood.setText("Modo Oscuro");
            lblMood.setForeground(Color.WHITE);
            btnsm.setBackground(new Color(64,128,156));
            inicio.setBackground(new Color(70,143,175));
            carrito.setBackground(new Color(70,143,175));
            favorito.setBackground(new Color(70,143,175));
            configuracion.setBackground(new Color(70,143,175));
            salir.setBackground(new Color(70,143,175));
            chk1.setForeground(Color.BLACK);
            chk2.setForeground(Color.BLACK);
            chk3.setForeground(Color.BLACK);
            panelP.setBackground(new Color(144,224,239));
            jLabel2.setForeground(Color.BLACK);
            lblpago.setForeground(Color.BLACK);
        }
        else{
            main.setBackground(new Color(35,35,35));
            opciones.setBackground(new Color(27,27,27));
            lblMood.setText("Modo Claro");
            lblMood.setForeground(Color.WHITE);
            btnsm.setBackground(new Color(40,40,40));
            inicio.setBackground(new Color(27,27,27));
            favorito.setBackground(new Color(27,27,27));
            carrito.setBackground(new Color(27,27,27));
            configuracion.setBackground(new Color(27,27,27));
            salir.setBackground(new Color(27,27,27));
            chk1.setForeground(Color.WHITE);
            chk2.setForeground(Color.WHITE);
            chk3.setForeground(Color.WHITE);
            panelP.setBackground(new Color(73,80,87));
            jLabel2.setForeground(Color.WHITE);
            lblpago.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_configuracionMouseClicked
    //Declaración de variables globales
    double precio1=0;
    double precio2=0;
    double precio3=0;

    public void producto1 (int orden){
        Carrito1 obj=new Carrito1();
        total = obj.totalPago();
        lblpago.setText(""+total);
        ImageIcon imagen1;
        switch(orden){
            case 0:
                precio1=150.00;
                imagen1 = new ImageIcon(this.getClass().getResource("/imgProductos/Zapatilla1.jpg"));
                lblimg1.setIcon(imagen1);
                lblp1.setText("S/. "+precio1);break;
            case 1:
                precio1=159.0;
                imagen1 = new ImageIcon(this.getClass().getResource("/imgProductos/pantalon1.jpg"));
                lblimg1.setIcon(imagen1);
                lblp1.setText("S/. "+precio1);break;
            case 2:
                precio1=70.0;
                imagen1 = new ImageIcon(this.getClass().getResource("/imgProductos/camisa1.jpg"));
                lblimg1.setIcon(imagen1);
                lblp1.setText("S/. "+precio1);break;
            case 3:
                precio1=249.0;
                imagen1 = new ImageIcon(this.getClass().getResource("/imgProductos/abrigo1.jpg"));
                lblimg1.setIcon(imagen1);
                lblp1.setText("S/. "+precio1);break;
        }
    }
    public void producto2 (int orden){
        ImageIcon imagen2;
        switch(orden){
            case 0:
                precio2=120.00;
                imagen2 = new ImageIcon(this.getClass().getResource("/imgProductos/Zapatilla2.jpg"));
                lblimg2.setIcon(imagen2);
                lblp2.setText("S/. "+precio2);break;
            case 1:
                precio2=139.0;
                imagen2 = new ImageIcon(this.getClass().getResource("/imgProductos/pantalon2.jpg"));
                lblimg2.setIcon(imagen2);
                lblp2.setText("S/. "+precio2);break;
            case 2:
                precio2=120.0;
                imagen2 = new ImageIcon(this.getClass().getResource("/imgProductos/camisa2.jpg"));
                lblimg2.setIcon(imagen2);
                lblp2.setText("S/. "+precio2);break;
            case 3:
                precio2=270.0;
                imagen2 = new ImageIcon(this.getClass().getResource("/imgProductos/abrigo2.jpg"));
                lblimg2.setIcon(imagen2);
                lblp2.setText("S/. "+precio2);break;
        }
    }
    public void producto3 (int orden){
        ImageIcon imagen3;
        switch(orden){
            case 0:
                precio3=200.0;
                imagen3 = new ImageIcon(this.getClass().getResource("/imgProductos/Zapatilla3.jpg"));
                lblimg3.setIcon(imagen3);
                lblp3.setText("S/. "+precio3);break;
            case 1:
                precio3=209.0;
                imagen3 = new ImageIcon(this.getClass().getResource("/imgProductos/pantalon3.jpg"));
                lblimg3.setIcon(imagen3);
                lblp3.setText("S/. "+precio3);break;
            case 2:
                precio3=100.0;
                imagen3 = new ImageIcon(this.getClass().getResource("/imgProductos/camisa3.jpg"));
                lblimg3.setIcon(imagen3);
                lblp3.setText("S/. "+precio3);break;
            case 3:
                precio3=230.0;
                imagen3 = new ImageIcon(this.getClass().getResource("/imgProductos/abrigo3.jpg"));
                lblimg3.setIcon(imagen3);
                lblp3.setText("S/. "+precio3);break;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sistema.PanelRound btnsm;
    private javax.swing.JPanel carrito;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JPanel configuracion;
    private javax.swing.JPanel favorito;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblMood;
    private javax.swing.JLabel lblc;
    private javax.swing.JLabel lblcarrito;
    private javax.swing.JLabel lblconfiguracion;
    private javax.swing.JLabel lblf;
    private javax.swing.JLabel lblfavorito;
    private javax.swing.JLabel lbli;
    private javax.swing.JLabel lblimg1;
    private javax.swing.JLabel lblimg2;
    private javax.swing.JLabel lblimg3;
    private javax.swing.JLabel lblinicio;
    private javax.swing.JLabel lblm;
    private javax.swing.JLabel lblp1;
    private javax.swing.JLabel lblp2;
    private javax.swing.JLabel lblp3;
    private javax.swing.JLabel lblpago;
    private javax.swing.JLabel lbls;
    private javax.swing.JLabel lblsalir;
    private javax.swing.JPanel main;
    private Sistema.PanelRound opciones;
    private javax.swing.JPanel panelP;
    private javax.swing.JPanel product1;
    private javax.swing.JPanel product2;
    private javax.swing.JPanel product3;
    private javax.swing.JPanel salir;
    private Sistema.PanelRound salir1;
    // End of variables declaration//GEN-END:variables
}
