/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema;

import java.awt.Color;
import javax.swing.JOptionPane;
import Clases.Cuentas;
import java.util.ArrayList;

/**
 *
 * @author CRISTHIAN
 */
public class seguridad extends javax.swing.JFrame {

    ArrayList <Cuentas> data=new ArrayList<>();
    public static seguridad controller;

    
    public seguridad() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Login");
    }
    public static seguridad getInstance(){
        if(controller == null)
	    controller = new seguridad();
	return controller;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new Sistema.PanelRound();
        jPanel1 = new javax.swing.JPanel();
        salirp = new javax.swing.JLabel();
        panelRound1 = new Sistema.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtc = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        login = new Sistema.PanelRound();
        jPanel2 = new javax.swing.JPanel();
        txtl = new javax.swing.JLabel();
        su = new javax.swing.JPanel();
        sc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(230, 57, 70));
        salir.setRoundBottomLeft(15);
        salir.setRoundBottomRight(10);
        salir.setRoundTopLeft(10);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(2, 62, 138));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 57, 70), 2, true));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salirp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        salirp.setForeground(new java.awt.Color(255, 255, 255));
        salirp.setText("×");
        jPanel1.add(salirp, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 20, 30));

        javax.swing.GroupLayout salirLayout = new javax.swing.GroupLayout(salir);
        salir.setLayout(salirLayout);
        salirLayout.setHorizontalGroup(
            salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
        salirLayout.setVerticalGroup(
            salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 0, 35, 35));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("INICIAR SESIÓN");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Usuario");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, -1));

        txtu.setForeground(new java.awt.Color(204, 204, 204));
        txtu.setText("Ingrese su nombre de usuario");
        txtu.setBorder(null);
        txtu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuFocusGained(evt);
            }
        });
        panelRound1.add(txtu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 162, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contraseña.png"))); // NOI18N
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtc.setForeground(new java.awt.Color(204, 204, 204));
        txtc.setText("*******");
        txtc.setBorder(null);
        txtc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcFocusGained(evt);
            }
        });
        panelRound1.add(txtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 162, -1));

        jLabel8.setForeground(new java.awt.Color(159, 159, 159));
        jLabel8.setText("@unmsm.edu.pe");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        login.setBackground(new java.awt.Color(2, 62, 138));
        login.setRoundBottomLeft(10);
        login.setRoundBottomRight(10);
        login.setRoundTopLeft(10);
        login.setRoundTopRight(10);
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(2, 62, 138));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(34, 87, 122), 2, true));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtl.setForeground(new java.awt.Color(255, 255, 255));
        txtl.setText("Ingresar");
        jPanel2.add(txtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 60, 30));

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        panelRound1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 270, 90, 30));

        su.setBackground(new java.awt.Color(170, 170, 170));

        javax.swing.GroupLayout suLayout = new javax.swing.GroupLayout(su);
        su.setLayout(suLayout);
        suLayout.setHorizontalGroup(
            suLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        suLayout.setVerticalGroup(
            suLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelRound1.add(su, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 160, 1));

        sc.setBackground(new java.awt.Color(170, 170, 170));

        javax.swing.GroupLayout scLayout = new javax.swing.GroupLayout(sc);
        sc.setLayout(scLayout);
        scLayout.setHorizontalGroup(
            scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        scLayout.setVerticalGroup(
            scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelRound1.add(sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 241, 160, 1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 360, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 438));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked
    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir.setBackground(Color.WHITE);
        salirp.setForeground(new Color(230,57,70));
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setBackground(new Color(230,57,70));
        salirp.setForeground(Color.WHITE);
    }//GEN-LAST:event_salirMouseExited
    public void llenarm(Cuentas a){
        data.add(a);
    }
    
    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        String clave, user;
        clave=txtc.getText();
        user=txtu.getText();

        if (user.equalsIgnoreCase("usuario1")&&clave.equals("2022")){
            JOptionPane.showMessageDialog(this,"BIENVENIDO ESTIMADO USUARIO");
            Principal obj=new Principal();
            obj.setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this,"Usuario y/o contraseña INCORRECTOS.");
            txtc.setText("");
        }
    }//GEN-LAST:event_loginMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(Color.WHITE);
        txtl.setForeground(new Color(2,62,138));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(new Color(2,62,138));
        txtl.setForeground(Color.WHITE);
    }//GEN-LAST:event_loginMouseExited

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
   
    }//GEN-LAST:event_salirMousePressed

    private void txtcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcFocusGained
    if (String.valueOf(txtc.getPassword()).equals("*******")){
        txtc.setText("");
        txtc.setForeground(Color.black);
    }                                 
    if (txtu.getText().equals("")){
        txtu.setText("Ingrese su nombre de usuario");
        txtu.setForeground(new Color(204,204,204));
    }                             
    sc.setBackground(new Color(0,119,182));
    sc.setSize(160,2);
    su.setSize(160,1);
    su.setBackground (new Color(170,170,170));
    }//GEN-LAST:event_txtcFocusGained

    private void txtuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuFocusGained
        if (txtu.getText().equals("Ingrese su nombre de usuario")){
            txtu.setText("");
            txtu.setForeground(Color.black);
        }
        if (String.valueOf(txtc.getPassword()).equals("")){
            txtc.setText("*******");
            txtc.setForeground(new Color(204,204,204));
        }
        su.setBackground(new Color(0,119,182));
        su.setSize(160,2);
        sc.setSize(160,1);
        sc.setBackground(new Color(170,170,170));
    }//GEN-LAST:event_txtuFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seguridad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private Sistema.PanelRound login;
    private Sistema.PanelRound panelRound1;
    private Sistema.PanelRound salir;
    private javax.swing.JLabel salirp;
    private javax.swing.JPanel sc;
    private javax.swing.JPanel su;
    private javax.swing.JPasswordField txtc;
    private javax.swing.JLabel txtl;
    private javax.swing.JTextField txtu;
    // End of variables declaration//GEN-END:variables
}
